### ISSUE TITLE
littler

### ISSUE THREAD

**Issue by danhalligan** [Oefenweb/ansible-r#10]
Hi again,

FYI, I've forked this repository again and made modifications to remove the littler dependency (and just use Rscript instead which is included with the standard R installation). I did this firstly because its one less dependency, but also because I noticed a weird issue with littler for bioconductor package installations. I can't quite figure out what's going on, but it looks like when running the script `R-install-pacakge` through littler, bioconductor attempted to install out of date packages if they'd been recently updated, but I don't see this issue with `Rscript`. Anyway, this solves an issue for me, and if I get chance I'll investigate. If your interested in incorporating this change I can issue a pull request.

Best,
Dan

**Comment by tersmitten** [comment]
Feel free to open a PR. Thanks in advance.

**Comment by tersmitten** [comment]
Fixed in #12
