### ISSUE TITLE
Add option to change status of apt packages

### ISSUE THREAD

**Issue by danhalligan** [Oefenweb/ansible-r#13]
Currently, for any installed apt dependencies for this ansible role (`r-base`, `r-base-dev`) and any "additional" installs (`littler` by default), the `state` (defined by the [ansible apt module](http://docs.ansible.com/ansible/apt_module.html)) is hardcoded to be `latest`. This means to install any packages, you will also be forced to upgrade R to the latest version.

Ideally, I'd like to have an option to change the `state` variable for apt packages. to avoid upgrades (e.g. by setting it to `present` rather than `latest`.

I'm just working on being able to add this by adding new variables to `defaults/main.yml`. I'll let you know when it's ready and hope you'll accept a pull request again (or help add this functionality any other way you see fit).

**Comment by tersmitten** [comment]
I just added this feature to some other roles of us, I can add it for you tomorrow.

**Comment by danhalligan** [comment]
OK great. Let me know if you need help, otherwise I'll leave it up to you.

**Comment by danhalligan** [comment]
It might also be useful to not require an apt installation of R at all, e.g. If R was compiled from source. Just a though my in case it affects coding for this issue.

**Comment by tersmitten** [comment]
Fixed in https://github.com/Oefenweb/ansible-r/commit/da654108d6e152625ced0413f9831441e51d0f48

**Comment by tersmitten** [comment]
I rather not compile it by hand if it's not really necessary.

**Comment by danhalligan** [comment]
Does this feature depend on installing https://github.com/Oefenweb/ansible-apt?
