### ISSUE TITLE
Can't install a role using Ansible Galaxy

### ISSUE THREAD

**Issue by lesniakania** [Oefenweb/ansible-r#14]
```bash
- downloading role 'ansible-r', owned by
 [WARNING]: - ansible-r was NOT installed successfully: Role has no field named u'owner'
```

And it's not actually only a warning. The role was indeed not installed :]

**Comment by tersmitten** [comment]
I don't think this a problem on our side. Is it possible that it is related to https://github.com/ansible/ansible/issues/19469?

**Comment by lesniakania** [comment]
Hm. Not sure, I'm new to Ansible. I try to install your playbook from Ansible Galaxy according to http://docs.ansible.com/ansible/galaxy.html this way:

```
- src:
  name: ansible-r
  version: 1.2.5
```

**Comment by tersmitten** [comment]
Do you want to install from Github or Galaxy?

**Comment by tersmitten** [comment]
As I understand (but I don't use Galaxy) this should work:

```
- src: tersmitten.r
  version: 1.2.5
```

```
- src: https://github.com/Oefenweb/ansible-r
  version: 1.2.5
```

**Comment by lesniakania** [comment]
Yeah, I've already installed using the second option. It may be kind of obvious but maybe putting this in README is a good idea.
