### ISSUE TITLE
Install packages from GitHub

### ISSUE THREAD

**Issue by brooklynbagel** [Oefenweb/ansible-r#16]
Not all packages are available on CRAN or BioConductor. Most of these are accessible from GitHub although there are other supposed sources such as BitBucket as well. I was thinking of adding an additional R package installation script and associated task and variable to install from these other sources.

**Comment by tersmitten** [comment]
Seems like a nice addition. I would be happy to merge it. 

But installation of these packages might be a bit more complicated as install_github depends on devtools and devtools depends on some Debian packages.

**Comment by mbeigel** [comment]
That's true and a fair point - I was thinking it since it would be optional to use any additional dependencies could be added to the README as optional but required if you want that functionality.

**Comment by tersmitten** [comment]
Feel free to give it a try and see how that works out.

**Comment by mbeigel** [comment]
Sorry about the delay. I've got a proposed solution #17
