### ISSUE TITLE
Add bionic support

### ISSUE THREAD

**Issue by thiagogomesverissimo** [Oefenweb/ansible-r#24]
Cran released the bionic repository:

https://cran.rstudio.com/bin/linux/ubuntu/bionic-cran35/

I can work in this role to implement this support if it is ok...

**Comment by tersmitten** [comment]
Do you also want to add 3.5 support for `trusty` and `xenial`?

https://cran.rstudio.com/bin/linux/ubuntu/

**Comment by tersmitten** [comment]
Can you give a short description on how you want to tackle this?

**Comment by thiagogomesverissimo** [comment]
There are a lot of ways, but I followed this one:

1. define a new default ansible boolean variable: r_cran35, so it is possible choose if role will add repository cran35
2. In vars, create a list r_repository_cran35 with correct deb path
3. In tasks, if r_cran35 is True, add  the correct apt repository

**Comment by thiagogomesverissimo** [comment]
By the way, the PR https://github.com/Oefenweb/ansible-r/pull/27
