### ISSUE TITLE
deprecation of result|version_compare

### ISSUE THREAD

**Issue by bomeara** [Oefenweb/ansible-r#31]
Thank you for the extremely helpful playbook. I'm getting this notification:

```
TASK [oefenweb.r : repository | add cran-r] ***************************************************************************************************************************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|version_compare` use `result is version_compare`. This feature will be removed in version
2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

I *think* it's fussy about https://github.com/Oefenweb/ansible-r/blob/2b4f046083355222d4bcb42a22070550800b104a/defaults/main.yml#L3 but I am very new to ansible, so I could be completely wrong.

**Comment by tersmitten** [comment]
You are correct, there's deprecation code in there :-) Can you propose a fix?

**Comment by bomeara** [comment]
I *think* changing it to `{{ ansible_distribution_version is version('18.04', '>=') }}` would work. There's documentation about this [here](https://docs.ansible.com/ansible/2.6/user_guide/playbooks_tests.html), I believe.

**Comment by tersmitten** [comment]
Can you make a pull request?

**Comment by bomeara** [comment]
Note I haven't run a test to make sure this works -- not sure if you have travis or similar set up for this repo (I'm still new to ansible, so I don't know how unit testing works). And again, thank you for the useful playbook!

**Comment by tersmitten** [comment]
Travis CI is setup, but you can also do a vagrant up in this directory (assuming you have virtualbox and vagrant installed)
