### ISSUE TITLE
Need to install dirmngr from apt

### ISSUE THREAD

**Issue by thiagogomesverissimo** [Oefenweb/ansible-r#36]
It is necessary install dirmngr package before run this role, error for debian 9 when the roles tries to add the gpg key:
```
"Warning: apt-key output should no
t be parsed (stdout is not a terminal)\ngpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory\ng
```

**Comment by tersmitten** [comment]
https://github.com/Oefenweb/ansible-percona-toolkit/blob/master/tasks/repository.yml#L3

**Comment by tersmitten** [comment]
Unfortunate that it is not working. However Debian (9) is not supported

**Comment by tersmitten** [comment]
Maybe you can update https://github.com/Oefenweb/ansible-r/pull/34
