### ISSUE TITLE
bioconductor

### ISSUE THREAD

**Issue by danhalligan** [Oefenweb/ansible-r#7]
Hi, I'm just wondering if you would consider adding support to install R packages via bioconductor. The install process is somewhat different to `install.packages()`:

  - <https://www.bioconductor.org/install/>

There is some rough code in one of the comments on this blog post:

  - https://svendvanderveken.wordpress.com/2014/02/25/snippet-to-install-r-packages-with-ansible/

If not, would you consider a pull request if I attempted an implementation?

**Comment by tersmitten** [comment]
That would be a nice addition. Feel free to give it try!

Make sure to have a look at: https://github.com/Oefenweb/ansible-r/blob/master/templates/usr/local/bin/R-install-package.j2 and the remove script in the same folder.

Adding a `type` property to `r_packages` could be a solution. What do think?

**Comment by danhalligan** [comment]
OK great!  Ansible is all new to me, so I'm still figuring things out. Currently, I'm looking at adding a separate `bioconductor_packages` key, but I'm happy to admit this not be best...

**Comment by danhalligan** [comment]
OK I've forked your repository and made some updates which pass some basic tests. If you like - have a look and check over the code. As I say, I'm new to ansible, so it might be worth checking. I went with your idea of adding a `type` property though edited the `R-install-package.j2 script` (as well as adding a test for a bioconductor install).

If your happy, I'll issue a pull request to get this change incorporated.

**Comment by tersmitten** [comment]
I'll have a look at it soon

**Comment by danhalligan** [comment]
Just wondering if you'd had a chance to look over this yet -- I think the code is pretty solid

**Comment by tersmitten** [comment]
Fixed in #9

**Comment by danhalligan** [comment]
Thanks!
